# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c6438cf9b46b37427026556abe77e811d17d8b85de74eb0c8548707855c5670c8ce031bc9184ae6e86974dbb162471324f863f1e816b69fc2b7ec5fa0876017

test:
  secret_key_base: f4b7277e0ba942ea2da16f9463f6bb572a8986e9b9ff67659faeffbbc6095a9f859c829b2bcce2bc6f86f4f12f2ba12f873f1cc8b2dc831f2c6d4a9329ace326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
